In [1]:
import numpy as np
import cv2



In [2]:
img = cv2.imread('./data/friends.jpg')

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()


In [3]:
# load cascade classifer

haar = cv2.CascadeClassifier('./data/haarcascade_frontalface_default.xml')

In [9]:
# step 1 : convert to gray scale

image = img.copy()

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# step 2 : apply grayscale image to cascde classifier

face_rect = haar.detectMultiScale(gray_img, scaleFactor=1.3, minNeighbors=5)


In [6]:
print(face_rect)

[[126   4  68  68]
 [149 259  30  30]
 [128 107  96  96]
 [255  90  95  95]
 [407  92  95  95]]


In [10]:
# step 3 : draw rectangle

for x,y,w,h in face_rect:
    cv2.rectangle(image, (x,y), (x+w, y+h), (0,255,0), 2)


cv2.imshow('detected faces', image)
cv2.waitKey()
cv2.destroyAllWindows()


## Real Time Face Detection Using OpenCV


In [13]:
cap = cv2.VideoCapture('./data/video.mp4')

while True:
    ret, frame = cap.read()
    
    if not ret:
        break
        
    gray_img = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    face_rect = haar.detectMultiScale(gray_img, scaleFactor=1.3, minNeighbors=5)
    
    for x,y,w,h in face_rect:
        cv2.rectangle(frame, (x,y), (x+w, y+h), (0,255,0), 2)
        
    cv2.imshow('video', frame)
    
    if cv2.waitKey(1) == 27:  # means wait for 1ms and if esc key is pressed then break
        break

cap.release()
cv2.destroyAllWindows()
